### ISSUE TITLE
DBの構造体の作成

### ISSUE THREAD

**Issue by xxarupakaxx** [hackathon-21winter-05/HiQidas#1]
[これ](https://md.trap.jp/G0ypWlq8Sc2_t2cJV8qxrA?view)通りに構造体を`gorm`で作る

一気に作るよりも個別のほうがよさそうかな

- [ ] users
- [ ] histories
- [ ] sheets
- [ ] hiqidashis
- [ ] images
- [ ] connections

**Comment by xxarupakaxx** [comment]
消せるためにもhiqidashisと、sheetsにDeletedAtを追加します（履歴は消さなくてもよさそう)

**Comment by logica0419** [comment]
hiqidashiは、直接削除する時レコード完全削除でいい気がしている
削除しても履歴を残しときたいとしたらheyaかな
heyaにarchived / deletedみたいなBoolカラムを用意して判別しておくと良い気がする
deleted_atって興味あるんかみんな？表示しなくて良いなら残す意味はない

**Comment by xxarupakaxx** [comment]
何も考えずに適当なこと言ったけどgormはgorm.deletedAtに何かしら意味あるかな〜って思って言っただけで深い意味はないです…

**Comment by logica0419** [comment]
いや、論理削除ってモードになるらしいから、意味はあるっぽい(今調べた)
ただ論理削除したら結局アプリからは検索全くできなくなっちゃうから、アーカイブを検索するモードとかつけたいならdeletedみたいなオリジナルのカラムを作ってやるのが良いかも
https://gorm.io/ja_JP/docs/delete.html#論理削除

**Comment by logica0419** [comment]
あとcreated_atとupdated_atってgormのやつ使わなくて良いの？(良くわかってないが)

**Comment by logica0419** [comment]
どうしたいか言っといて

**Comment by xxarupakaxx** [comment]
Hiqidashiの色情報も持っておかないとだ
