### ISSUE TITLE
エンドポイント・スキーマ設計 - Protocol Buffers

### ISSUE THREAD

**Issue by xxarupakaxx** [hackathon-21winter-05/HiQidas#2]
- [ ] GET /users
- [ ] POST /users
- [ ] GET /users/me
- [ ] PUT /users/me
- [ ] GET /users/me/icon
- [ ] GET /users/{userid}
- [ ] PUT /users/{userid}
- [ ] GET /sheets
- [ ] POST /sheets
- [ ] GET /sheets/{sheetid}
- [ ] POST /sheets/{sheetid}
- [ ] GET /sheets/{sheetid}/users
- [ ] GET /ws/{sheetid}
- [ ] GET /oauth/authorize
- [ ] POST /oauth/code

https://md.trap.jp/G0ypWlq8Sc2_t2cJV8qxrA?view#REST-API-%E3%82%A8%E3%83%B3%E3%83%89%E3%83%9D%E3%82%A4%E3%83%B3%E3%83%88

**Comment by xxarupakaxx** [comment]
/api 下

### Users
- GET /users/me　
- PUT /users/me
- GET /users/me/icon
- GET /users
- POST /users
- GET /users/{userid}
- PUT /users/{userid}
    - admin only

### SheetS
- GET /sheets
- POST /sheets
- GET /sheets/{sheetid}
- PUT /sheets/{sheetid}
- GET /sheets/{sheetid}/user

### WS
- GET /ws/{sheetid} 

### OAuth
- GET /oauth/redirect
- POST /oauth/code

**Comment by xxarupakaxx** [comment]
PRは一気にやるんじゃなくて一つ一つ定義してのほうがよさそう..?(プロトコルバッファ的に一気に宣言作成したほうがつかいやすいとかあったり？）

**Comment by logica0419** [comment]
PRはこまめに出しちゃってくれ
まだ仕様固まりきってないしできたやつから使いたい

**Comment by xxarupakaxx** [comment]
ありがとう！！
プロトコルバッファ初めて使うのでよくわからなくなったら聞きます..:bowing_man:
